num = list(range(1,22))
print(num)
print(f"The first 3 items in this list are: {num[:3]}")
print(f"The middle 3 items in this list are: {num[9:12]}")
print(f"The last 3 items in this list are: {num[-3:]}")
